apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    chart: airflow-1.6.0
    component: worker-horizontalpodautoscaler
    deploymentName: airflow-worker
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-worker
  namespace: airflow
spec:
  cooldownPeriod: 30
  maxReplicaCount: 12
  minReplicaCount: 0
  pollingInterval: 5
  scaleTargetRef:
    kind: StatefulSet
    name: airflow-worker
  triggers:
  - metadata:
      connectionFromEnv: AIRFLOW_CONN_AIRFLOW_DB
      query: SELECT ceil(COUNT(*)::decimal / 8) FROM task_instance WHERE (state='running' OR state='queued')
      targetQueryValue: "1"
    type: postgresql
---
