resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- |-
  apiVersion: v1
  data:
    connection: your-db-connection-in-base64
  kind: Secret
  metadata:
    name: airflow-airflow-result-backend
  ---
  apiVersion: v1
  data:
    connection: your-db-connection-in-base64
  kind: Secret
  metadata:
    name: airflow-airflow-metadata
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: airflow-webserver
  spec:
    type: ClusterIP
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: airflow-flower
  spec:
    type: ClusterIP
