apiVersion: v1
data:
  insecure: dHJ1ZQ==
  name: your-dag-repo-name-in-base64
  project: ZGFncw==
  sshPrivateKey: your-base64-ssh-key
  type: Z2l0
  url: your-dag-repo-url
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-dags
  namespace: argocd
type: Opaque
