namespace: airflow
helmCharts:
- name: airflow
  valuesFile: values.yaml
  includeCRDs: false
  releaseName: airflow
  version: 1.6.0
  repo: https://airflow.apache.org

resources:
- secrets.yaml

patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
      $patch: replace
    name: airflow-create-user
- |-
  apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
      $patch: replace
    name: airflow-run-airflow-migrations
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      $patch: replace
    name: airflow-broker-url
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      $patch: replace
    name: airflow-redis-password

