apiVersion: v1
data:
  fernet-key: base64-encoded-secret
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-fernet-key
  namespace: airflow

---
apiVersion: v1
data:
  gitSshKey: base64-encoded-ssh-key
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-ssh-git-secret
  namespace: airflow
---
apiVersion: v1
data:
  webserver-secret-key:  base64-encoded-web-secret
kind: Secret
metadata:
  creationTimestamp: null
  name: airflow-webserver-secret-key
  namespace: airflow
