airflowVersion: 2.3.4
config:
  api:
    auth_backends: airflow.api.auth.backend.basic_auth
  celery:
    worker_concurrency: 8
  celery_kubernetes_executor:
    kubernetes_queue: kubernetes
  core:
    colored_console_log: 'False'
    dags_folder: '{{ include "airflow_dags" . }}'
    executor: '{{ .Values.executor }}'
    load_examples: 'False'
    remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
    enable_xcom_pickling: 'True'
    max_active_runs_per_dag: 512
    max_active_tasks_per_dag: 512
    parallelism: 1024
    max_tis_per_query: 1024
  kubernetes:
    airflow_configmap: '{{ include "airflow_config" . }}'
    airflow_local_settings_configmap: '{{ include "airflow_config" . }}'
    multi_namespace_mode: '{{ if .Values.multiNamespaceMode }}True{{ else }}False{{ end }}'
    namespace: '{{ .Release.Namespace }}'
    pod_template_file: '{{ include "airflow_pod_template_file" . }}/pod_template_file.yaml'
    worker_container_repository: >-
      {{ .Values.images.airflow.repository | default
      .Values.defaultAirflowRepository }}
    worker_container_tag: '{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag }}'
  logging:
    colored_console_log: 'False'
    remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
  metrics:
    statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
    statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
    statsd_port: 9125
    statsd_prefix: airflow
  scheduler:
    run_duration: 41460
    statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
    statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
    statsd_port: 9125
    statsd_prefix: airflow
  webserver:
    enable_proxy_fix: 'True'
    rbac: 'True'
dags:
  gitSync:
    branch: master
    containerName: git-sync
    depth: 1
    enabled: true
    env: []
    extraVolumeMounts: []
    maxFailures: 0
    repo: your-dags-repo
    resources: {}
    rev: HEAD
    securityContext: {}
    subPath: "/dags"
    sshKeySecret: airflow-ssh-git-secret
    knownHosts: "known-host"
    uid: 65533
    wait: 30
  persistence:
    accessMode: ReadWriteOnce
    enabled: false
    existingClaim: null
    size: 1Gi
    storageClassName: null
postgresql:
  enabled: false
data:
  metadataConnection:
    db: postgres
    host: postgresql-ip
    pass: postgresql-password
    port: 5432
    protocol: postgresql
    sslmode: disable
    user: postgres
defaultAirflowRepository: your-repo
defaultAirflowTag: your-tag
env: []
executor: CeleryExecutor
extraConfigMaps: {}
fernetKeySecretName: airflow-fernet-key
fullnameOverride: ''
gid: 0
images:
  airflow:
    pullPolicy: Always
    repository: null
    tag: null
  flower:
    pullPolicy: IfNotPresent
    repository: null
    tag: null
  gitSync:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/git-sync/git-sync
    tag: v3.4.0
  migrationsWaitTimeout: 60
  pod_template:
    pullPolicy: IfNotPresent
    repository: null
    tag: null
  redis:
    pullPolicy: IfNotPresent
    repository: redis
    tag: 6-bullseye
  statsd:
    pullPolicy: IfNotPresent
    repository: quay.io/prometheus/statsd-exporter
    tag: v0.22.8
  useDefaultImageForMigration: false
logs:
  persistence:
    enabled: false
    existingClaim: null
    size: 30Gi
    storageClassName: null
ports:
  airflowUI: 8080
  flowerUI: 5555
  redisDB: 6379
  statsdIngest: 9125
  statsdScrape: 9102
  workerLogs: 8793
redis:
  enabled: true
  password: your-redis-password
flower:
  enabled: true
  service:
    type: LoadBalancer
  username: your-flower-user
  password: your-flower-password
registry:
  connection: {}
  secretName: null
uid: 50000
webserver:
  defaultUser:
    email: admin@example.com
    enabled: true
    firstName: admin
    lastName: user
    password: your-airflow-password
    role: Admin
    username: admin
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 10
    failureThreshold: 20
    periodSeconds: 30
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 10
    failureThreshold: 20
    periodSeconds: 30
  service:
    type: LoadBalancer
    ports:
      - name: airflow-ui
        port: 80
        targetPort: airflow-ui
webserverSecretKeySecretName: airflow-webserver-secret-key
workers:
  keda:
    cooldownPeriod: 30
    enabled: false
    maxReplicaCount: 10
    minReplicaCount: 0
    namespaceLabels: {}
    pollingInterval: 5
  persistence:
    enabled: true
    fixPermissions: false
    size: 30Gi
    storageClassName: null
  replicas: 2
migrateDatabaseJob:
  useHelmHooks: false
createUserJob:
  useHelmHooks: false
statsd:
  enabled: false

